[2023-12-18 13:02:45,044] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:07:45,163] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:12:45,280] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:15:52,843] INFO [Producer clientId=producer-3] Resetting the last seen epoch of partition connect-configs-0 to 0 since the associated topicId changed from null to IbF5gmv6SZyD2XmabuXxFw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,847] INFO Successfully processed removal of connector 'my-source-connect' (org.apache.kafka.connect.storage.KafkaConfigBackingStore:852)
[2023-12-18 13:15:52,848] INFO [Worker clientId=connect-1, groupId=connect-cluster] Connector my-source-connect config removed (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2053)
[2023-12-18 13:15:52,848] INFO [Worker clientId=connect-1, groupId=connect-cluster] Handling connector-only config update by stopping connector my-source-connect (org.apache.kafka.connect.runtime.distributed.DistributedHerder:669)
[2023-12-18 13:15:52,848] INFO [my-source-connect|worker] Stopping connector my-source-connect (org.apache.kafka.connect.runtime.Worker:423)
[2023-12-18 13:15:52,848] INFO [my-source-connect|worker] Scheduled shutdown for WorkerConnector{id=my-source-connect} (org.apache.kafka.connect.runtime.WorkerConnector:257)
[2023-12-18 13:15:52,849] INFO [Producer clientId=producer-2] Resetting the last seen epoch of partition connect-status-0 to 0 since the associated topicId changed from null to _oIidf5WTcyncK2ZVA9Xjw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,850] INFO [Producer clientId=producer-2] Resetting the last seen epoch of partition connect-status-4 to 0 since the associated topicId changed from null to _oIidf5WTcyncK2ZVA9Xjw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,850] INFO [Producer clientId=producer-2] Resetting the last seen epoch of partition connect-status-1 to 0 since the associated topicId changed from null to _oIidf5WTcyncK2ZVA9Xjw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,850] INFO [Producer clientId=producer-2] Resetting the last seen epoch of partition connect-status-2 to 0 since the associated topicId changed from null to _oIidf5WTcyncK2ZVA9Xjw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,851] INFO [Producer clientId=producer-2] Resetting the last seen epoch of partition connect-status-3 to 0 since the associated topicId changed from null to _oIidf5WTcyncK2ZVA9Xjw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:15:52,851] INFO [my-source-connect|worker] Completed shutdown for WorkerConnector{id=my-source-connect} (org.apache.kafka.connect.runtime.WorkerConnector:277)
[2023-12-18 13:15:52,853] INFO [Worker clientId=connect-1, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:229)
[2023-12-18 13:15:52,853] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:566)
[2023-12-18 13:15:52,857] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=12, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:627)
[2023-12-18 13:15:52,859] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=12, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:802)
[2023-12-18 13:15:52,860] INFO [my-source-connect|worker] Stopping connector my-source-connect (org.apache.kafka.connect.runtime.Worker:423)
[2023-12-18 13:15:52,860] WARN [my-source-connect|worker] Ignoring stop request for unowned connector my-source-connect (org.apache.kafka.connect.runtime.Worker:426)
[2023-12-18 13:15:52,861] WARN [my-source-connect|worker] Ignoring await stop request for non-present connector my-source-connect (org.apache.kafka.connect.runtime.Worker:451)
[2023-12-18 13:15:52,861] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished stopping tasks in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2342)
[2023-12-18 13:15:52,861] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished flushing status backing store in preparation for rebalance (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2361)
[2023-12-18 13:15:52,861] INFO [Worker clientId=connect-1, groupId=connect-cluster] Joined group at generation 12 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', leaderUrl='http://192.168.0.50:8083/', offset=16, connectorIds=[my-sink-connect], taskIds=[my-sink-connect-0], revokedConnectorIds=[my-source-connect], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2256)
[2023-12-18 13:15:52,862] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset 16 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1659)
[2023-12-18 13:15:52,862] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1687)
[2023-12-18 13:15:52,862] INFO [Worker clientId=connect-1, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:229)
[2023-12-18 13:15:52,862] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:566)
[2023-12-18 13:15:52,863] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=13, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:627)
[2023-12-18 13:15:52,865] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=13, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:802)
[2023-12-18 13:15:52,865] INFO [Worker clientId=connect-1, groupId=connect-cluster] Joined group at generation 13 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', leaderUrl='http://192.168.0.50:8083/', offset=16, connectorIds=[my-sink-connect], taskIds=[my-sink-connect-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2256)
[2023-12-18 13:15:52,866] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset 16 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1659)
[2023-12-18 13:15:52,866] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1687)
[2023-12-18 13:15:58,205] INFO JdbcSourceConnectorConfig values: 
	batch.max.rows = 100
	catalog.pattern = null
	connection.attempts = 3
	connection.backoff.ms = 10000
	connection.password = null
	connection.url = jdbc:mysql://localhost:3307/test
	connection.user = root
	db.timezone = UTC
	dialect.name = 
	incrementing.column.name = 
	mode = incrementing
	numeric.mapping = null
	numeric.precision.mapping = false
	poll.interval.ms = 5000
	query = 
	query.retry.attempts = -1
	query.suffix = 
	quote.sql.identifiers = ALWAYS
	schema.pattern = null
	table.blacklist = []
	table.monitoring.startup.polling.limit.ms = 10000
	table.poll.interval.ms = 60000
	table.types = [TABLE]
	table.whitelist = [test.users]
	timestamp.column.name = []
	timestamp.delay.interval.ms = 0
	timestamp.granularity = connect_logical
	timestamp.initial = null
	topic.prefix = my_topic_
	transaction.isolation.mode = DEFAULT
	validate.non.null = true
 (io.confluent.connect.jdbc.source.JdbcSourceConnectorConfig:376)
[2023-12-18 13:15:58,205] INFO AbstractConfig values: 
 (org.apache.kafka.common.config.AbstractConfig:376)
[2023-12-18 13:15:58,213] INFO [Worker clientId=connect-1, groupId=connect-cluster] Connector my-source-connect config updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2066)
[2023-12-18 13:15:58,213] INFO [Worker clientId=connect-1, groupId=connect-cluster] Rebalance started (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:229)
[2023-12-18 13:15:58,214] INFO [Worker clientId=connect-1, groupId=connect-cluster] (Re-)joining group (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:566)
[2023-12-18 13:15:58,216] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully joined group with generation Generation{generationId=14, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:627)
[2023-12-18 13:15:58,218] INFO [Worker clientId=connect-1, groupId=connect-cluster] Successfully synced group in generation Generation{generationId=14, memberId='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', protocol='sessioned'} (org.apache.kafka.connect.runtime.distributed.WorkerCoordinator:802)
[2023-12-18 13:15:58,218] INFO [Worker clientId=connect-1, groupId=connect-cluster] Joined group at generation 14 with protocol version 2 and got assignment: Assignment{error=0, leader='connect-1-5fe3efe7-8e24-423d-b70b-71765d4edb5e', leaderUrl='http://192.168.0.50:8083/', offset=17, connectorIds=[my-source-connect, my-sink-connect], taskIds=[my-sink-connect-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2256)
[2023-12-18 13:15:58,219] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connectors and tasks using config offset 17 (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1659)
[2023-12-18 13:15:58,219] INFO [Worker clientId=connect-1, groupId=connect-cluster] Starting connector my-source-connect (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1776)
[2023-12-18 13:15:58,219] INFO [my-source-connect|worker] Creating connector my-source-connect of type io.confluent.connect.jdbc.JdbcSourceConnector (org.apache.kafka.connect.runtime.Worker:300)
[2023-12-18 13:15:58,220] INFO [my-source-connect|worker] SourceConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	exactly.once.support = requested
	header.converter = null
	key.converter = null
	name = my-source-connect
	offsets.storage.topic = null
	predicates = []
	tasks.max = 1
	topic.creation.groups = []
	transaction.boundary = poll
	transaction.boundary.interval.ms = null
	transforms = []
	value.converter = null
 (org.apache.kafka.connect.runtime.SourceConnectorConfig:376)
[2023-12-18 13:15:58,220] INFO [my-source-connect|worker] EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	exactly.once.support = requested
	header.converter = null
	key.converter = null
	name = my-source-connect
	offsets.storage.topic = null
	predicates = []
	tasks.max = 1
	topic.creation.groups = []
	transaction.boundary = poll
	transaction.boundary.interval.ms = null
	transforms = []
	value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:376)
[2023-12-18 13:15:58,224] INFO [my-source-connect|worker] EnrichedSourceConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	exactly.once.support = requested
	header.converter = null
	key.converter = null
	name = my-source-connect
	offsets.storage.topic = null
	predicates = []
	tasks.max = 1
	topic.creation.default.exclude = []
	topic.creation.default.include = [.*]
	topic.creation.default.partitions = 1
	topic.creation.default.replication.factor = 1
	topic.creation.groups = []
	transaction.boundary = poll
	transaction.boundary.interval.ms = null
	transforms = []
	value.converter = null
 (org.apache.kafka.connect.runtime.SourceConnectorConfig$EnrichedSourceConnectorConfig:376)
[2023-12-18 13:15:58,225] INFO [my-source-connect|worker] EnrichedConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.confluent.connect.jdbc.JdbcSourceConnector
	errors.log.enable = false
	errors.log.include.messages = false
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	exactly.once.support = requested
	header.converter = null
	key.converter = null
	name = my-source-connect
	offsets.storage.topic = null
	predicates = []
	tasks.max = 1
	topic.creation.default.exclude = []
	topic.creation.default.include = [.*]
	topic.creation.default.partitions = 1
	topic.creation.default.replication.factor = 1
	topic.creation.groups = []
	transaction.boundary = poll
	transaction.boundary.interval.ms = null
	transforms = []
	value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:376)
[2023-12-18 13:15:58,225] INFO [my-source-connect|worker] Instantiated connector my-source-connect with version 10.6.3 of type class io.confluent.connect.jdbc.JdbcSourceConnector (org.apache.kafka.connect.runtime.Worker:322)
[2023-12-18 13:15:58,226] INFO [my-source-connect|worker] Finished creating connector my-source-connect (org.apache.kafka.connect.runtime.Worker:347)
[2023-12-18 13:15:58,226] INFO [my-source-connect|worker] Starting JDBC Source Connector (io.confluent.connect.jdbc.JdbcSourceConnector:71)
[2023-12-18 13:15:58,226] INFO [Worker clientId=connect-1, groupId=connect-cluster] Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1687)
[2023-12-18 13:15:58,226] INFO [my-source-connect|worker] JdbcSourceConnectorConfig values: 
	batch.max.rows = 100
	catalog.pattern = null
	connection.attempts = 3
	connection.backoff.ms = 10000
	connection.password = null
	connection.url = jdbc:mysql://localhost:3307/test
	connection.user = root
	db.timezone = UTC
	dialect.name = 
	incrementing.column.name = 
	mode = incrementing
	numeric.mapping = null
	numeric.precision.mapping = false
	poll.interval.ms = 5000
	query = 
	query.retry.attempts = -1
	query.suffix = 
	quote.sql.identifiers = ALWAYS
	schema.pattern = null
	table.blacklist = []
	table.monitoring.startup.polling.limit.ms = 10000
	table.poll.interval.ms = 60000
	table.types = [TABLE]
	table.whitelist = [test.users]
	timestamp.column.name = []
	timestamp.delay.interval.ms = 0
	timestamp.granularity = connect_logical
	timestamp.initial = null
	topic.prefix = my_topic_
	transaction.isolation.mode = DEFAULT
	validate.non.null = true
 (io.confluent.connect.jdbc.source.JdbcSourceConnectorConfig:376)
[2023-12-18 13:15:58,227] INFO [my-source-connect|worker] Attempting to open connection #1 to MySql (io.confluent.connect.jdbc.util.CachedConnectionProvider:79)
[2023-12-18 13:15:58,234] INFO [my-source-connect|worker] Unable to connect to database on attempt 1/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:86)
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:250)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	at io.confluent.connect.jdbc.JdbcSourceConnector.start(JdbcSourceConnector.java:94)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:193)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:218)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:363)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:346)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:146)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: GSS-API authentication exception
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:169)
	at org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket.process(SendGssApiAuthPacket.java:133)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:752)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
	... 20 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for Krb5ConnectorContext
	at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:269)
	at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:357)
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:117)
	... 24 more
[2023-12-18 13:16:08,236] INFO [my-source-connect|worker] Attempting to open connection #2 to MySql (io.confluent.connect.jdbc.util.CachedConnectionProvider:79)
[2023-12-18 13:16:08,242] INFO [my-source-connect|worker] Unable to connect to database on attempt 2/3. Will retry in 10000 ms. (io.confluent.connect.jdbc.util.CachedConnectionProvider:86)
java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:250)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	at io.confluent.connect.jdbc.JdbcSourceConnector.start(JdbcSourceConnector.java:94)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:193)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:218)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:363)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:346)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:146)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLException: GSS-API authentication exception
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:169)
	at org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket.process(SendGssApiAuthPacket.java:133)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:752)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
	... 20 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for Krb5ConnectorContext
	at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:269)
	at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:357)
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:117)
	... 24 more
[2023-12-18 13:16:18,253] INFO [my-source-connect|worker] Attempting to open connection #3 to MySql (io.confluent.connect.jdbc.util.CachedConnectionProvider:79)
[2023-12-18 13:16:18,258] ERROR [my-source-connect|worker] WorkerConnector{id=my-source-connect} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:201)
org.apache.kafka.connect.errors.ConnectException: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:59)
	at io.confluent.connect.jdbc.JdbcSourceConnector.start(JdbcSourceConnector.java:94)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:193)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:218)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:363)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:346)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:146)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:250)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	... 12 more
Caused by: java.sql.SQLException: GSS-API authentication exception
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:169)
	at org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket.process(SendGssApiAuthPacket.java:133)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:752)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
	... 20 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for Krb5ConnectorContext
	at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:269)
	at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:357)
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:117)
	... 24 more
[2023-12-18 13:16:18,260] ERROR [my-source-connect|worker] [Worker clientId=connect-1, groupId=connect-cluster] Failed to start connector 'my-source-connect' (org.apache.kafka.connect.runtime.distributed.DistributedHerder:1811)
org.apache.kafka.connect.errors.ConnectException: Failed to start connector: my-source-connect
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$startConnector$35(DistributedHerder.java:1782)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
	at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:146)
	at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:123)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to transition connector my-source-connect to state STARTED
	... 8 more
Caused by: org.apache.kafka.connect.errors.ConnectException: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:59)
	at io.confluent.connect.jdbc.JdbcSourceConnector.start(JdbcSourceConnector.java:94)
	at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:193)
	at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:218)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:363)
	at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:346)
	... 7 more
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect to address=(host=localhost)(port=3307)(type=master) : GSS-API authentication exception
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:66)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
	at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.getConnection(GenericDatabaseDialect.java:250)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.newConnection(CachedConnectionProvider.java:80)
	at io.confluent.connect.jdbc.util.CachedConnectionProvider.getConnection(CachedConnectionProvider.java:52)
	... 12 more
Caused by: java.sql.SQLException: GSS-API authentication exception
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:169)
	at org.mariadb.jdbc.internal.com.send.authentication.SendGssApiAuthPacket.process(SendGssApiAuthPacket.java:133)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:752)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:553)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
	... 20 more
Caused by: javax.security.auth.login.LoginException: No LoginModules configured for Krb5ConnectorContext
	at java.base/javax.security.auth.login.LoginContext.init(LoginContext.java:269)
	at java.base/javax.security.auth.login.LoginContext.<init>(LoginContext.java:357)
	at org.mariadb.jdbc.internal.com.send.authentication.gssapi.StandardGssapiAuthentication.authenticate(StandardGssapiAuthentication.java:117)
	... 24 more
[2023-12-18 13:22:45,408] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:27:45,529] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:32:45,643] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:37:45,769] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:42:45,880] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:47:45,999] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:52:46,123] INFO [AdminClient clientId=adminclient-10] Node 0 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-12-18 13:54:51,944] INFO [Producer clientId=producer-3] Resetting the last seen epoch of partition connect-configs-0 to 0 since the associated topicId changed from null to IbF5gmv6SZyD2XmabuXxFw (org.apache.kafka.clients.Metadata:402)
[2023-12-18 13:54:51,951] INFO [Worker clientId=connect-1, groupId=connect-cluster] Session key updated (org.apache.kafka.connect.runtime.distributed.DistributedHerder:2124)
